return {
-- 判定文字の表示サイズ
JUDGEF_WIDTH = 128,
JUDGEF_HEIGHT = 29,

-- 判定文字画像の分割数(縦)
DIVY_F_PG = 1,
DIVY_F_GR = 1,
DIVY_F_GD = 1,
DIVY_F_BD = 1,
DIVY_F_PR = 1,

-- 判定数字の表示サイズ(1桁)	
JUDGEN_WIDTH = 40,
JUDGEN_HEIGHT = 55,

-- 判定数字画像の分割数(縦)
DIVY_N_PG = 1,
DIVY_N_GR = 1,
DIVY_N_GD = 1,

-- 判定文字と判定数字の間のスペース
JUDGE_SPACE = 5,

-- 表示形式(1:横1列 2:横2列数字上 3:横2列数字下)
JUDGE_FORMAT = 3,

-- 判定文字・数字の拡縮アニメーション設定
--[[
JUDGE_SCALE_ANIMATION_TIME = 100,
JUDGEF_SCALE_ANIMATION_WIDTH = 60,
JUDGEF_SCALE_ANIMATION_HEIGHT = 16,
JUDGEF_SCALE_ANIMATION_OPACITY = 128,
JUDGEN_SCALE_ANIMATION_WIDTH = 0,
JUDGEN_SCALE_ANIMATION_HEIGHT = 0,
JUDGEN_SCALE_ANIMATION_OPACITY = 255,
--]]

-- アニメーション再生周期	
JUDGE_ANIMATION_CYCLE_PG = 125,
JUDGE_ANIMATION_CYCLE_GR = 75,
JUDGE_ANIMATION_CYCLE_GD = 75,
JUDGE_ANIMATION_CYCLE_BD = 75,
JUDGE_ANIMATION_CYCLE_PR = 75
}