return {
-- 判定文字の表示サイズ
JUDGEF_WIDTH = 204,
JUDGEF_HEIGHT = 58,

-- 判定文字画像の分割数(縦)
DIVY_F_PG = 3,
DIVY_F_GR = 2,
DIVY_F_GD = 2,
DIVY_F_BD = 2,
DIVY_F_PR = 2,

-- 判定数字の表示サイズ(1桁)	
JUDGEN_WIDTH = 44,
JUDGEN_HEIGHT = 58,

-- 判定数字画像の分割数(縦)
DIVY_N_PG = 3,
DIVY_N_GR = 2,
DIVY_N_GD = 2,

-- 判定文字と判定数字の間のスペース
JUDGE_SPACE = 20,

-- 表示形式(1:横1列 2:横2列数字上 3:横2列数字下)
JUDGE_FORMAT = 1,

-- 判定文字・数字の拡縮アニメーション設定
--[[
JUDGE_SCALE_ANIMATION_TIME = 100,
JUDGEF_SCALE_ANIMATION_WIDTH = 60,
JUDGEF_SCALE_ANIMATION_HEIGHT = 16,
JUDGEF_SCALE_ANIMATION_OPACITY = 128,
JUDGEN_SCALE_ANIMATION_WIDTH = 0,
JUDGEN_SCALE_ANIMATION_HEIGHT = 0,
JUDGEN_SCALE_ANIMATION_OPACITY = 255,
--]]

-- アニメーション再生周期	
JUDGE_ANIMATION_CYCLE_PG = 125,
JUDGE_ANIMATION_CYCLE_GR = 75,
JUDGE_ANIMATION_CYCLE_GD = 75,
JUDGE_ANIMATION_CYCLE_BD = 75,
JUDGE_ANIMATION_CYCLE_PR = 75
}