return {
	property = {
		{name = "スキン構成の保存 SaveSkinConfig", def = "OFF"},
		{name = "エラーメッセージ表示 DisplayErrorMessage", def = "OFF"},
		{name = "画面解像度 Resolution", def = "FHD(1920x1080)"},
		{name = "判定文字の置換(Hub)", def = "OFF"},
		{name = "ノーツの置換(Hub)", def = "OFF"},
		{name = "ボムの置換(Hub)", def = "OFF"},
		{name = "フルコンボエフェクトの置換(Hub)", def = "OFF"},
		{name = "SUDDENカバーの置換(Hub)", def = "OFF"},
		{name = "HIDDENカバーの置換(Hub)", def = "OFF"},
		{name = "LIFTカバーの置換(Hub)", def = "OFF"},
		{name = "FINISHカバーの置換(Hub)", def = "OFF"},
	},
	filepath = {
		{name = "設定ファイル Settings", def = "REMI-S-AC-CS1P.lua"},
		{name = "システムフォント Font", def = "mgenplus-1c-bold.ttf"},
		{name = "フレーム Frame", def = "default"},
		{name = "背景 Background", def = "off.png"},
		{name = "汎用BGA/BGI NoBgaImage", def = "default.png"},
		{name = "鍵盤デザイン Device", def = "04_aqua"},
		{name = "グルーブゲージ GrooveGauge", def = "remi-s"},
		{name = "スコアグラフ ScoreGraph", def = "default_1p"},
		{name = "ソングプログレスバー SongProgress", def = "aqua"},
		{name = "楽曲情報 SongInfo", def = "default"},
		{name = "BPM Bpm", def = "remi-s"},
		{name = "スコア Score", def = "default"},
		{name = "スコアレート ScoreRate", def = "default"},
		{name = "MAXコンボ MaxCombo", def = "default"},
		{name = "自己ベストスコア差 DiffBestScore", def = "default"},
		{name = "ターゲットスコア差 DiffTargetScore", def = "default"},
		{name = "ランクペース RankPace", def = "block"},
		{name = "ジャッジカウント JudgeCount", def = "default"},
		{name = "タイムレフト TimeLeft", def = "default"},
		{name = "マスコット Mascot", def = "off.png"},
		{name = "動くマスコット MovingMascot", def = "off.png"},
		{name = "ぽみゅキャラ Pmchara", def = "off"},
		{name = "タイミングビジュアライザ TimingVisualizer", def = "default"},
		{name = "ヒットエラービジュアライザ HitErrorVisualizer", def = "off"},
		{name = "ジャッジグラフ JudgeGraph", def = "default"},
		{name = "BPMグラフ BpmGraph", def = "default"},
		{name = "レーン背景 LaneBackground", def = "default.png"},
		{name = "レーン Lane", def = "beat"},
		{name = "グロー Glow", def = "aqua"},
		{name = "判定ライン JudgeLine", def = "blue"},
		{name = "ノーツ notes", def = "simple"},
		{name = "キービーム Keybeam", def = "default"},
		{name = "レーンカバー1P LaneCover1P", def = "default.png"},
		{name = "リフトカバー1P LiftCover1P", def = "default.png"},
		{name = "HIDDENカバー1P HiddenCover1P", def = "default.png"},
		{name = "フィニッシュカバー1P FinishCover1P", def = "default.png"},
		{name = "カバー数値 CoverDuration", def = "default2"},
		{name = "ボム Bomb", def = "photonring"},
		{name = "判定文字 Judge", def = "default2"},
		{name = "判定タイミング JudgeDetail", def = "default2-fastslow"},
		{name = "ゴーストスコア GhostScore", def = "default2-best"},
		{name = "ロード中演出 Loading", def = "default"},
		{name = "開始演出 Start", def = "default"},
		{name = "クリア演出 Clear", def = "off"},
		{name = "フルコンボ演出 FullCombo", def = "default"},
		{name = "閉店演出 Failed", def = "default"},
		{name = "終了演出 Close", def = "default"},
		{name = "拡張機能1 Extension1", def = "BGA枠表示"},
		{name = "拡張機能2 Extension2", def = "off"},
		{name = "拡張機能3 Extension3", def = "off"},
		{name = "拡張機能4 Extension4", def = "off"},
		{name = "拡張機能5 Extension5", def = "off"},
		{name = "拡張機能6 Extension6", def = "off"},
		{name = "拡張機能7 Extension7", def = "off"},
		{name = "拡張機能8 Extension8", def = "off"},
		{name = "拡張機能9 Extension9", def = "off"},
		{name = "拡張機能10 Extension10", def = "off"},
		{name = "SUDDENカバー(Hub)", def = "cp_wizardcloak.png"},
		{name = "HIDDENカバー(Hub)", def = "cp_wizardcloak.png"},
		{name = "LIFTカバー(Hub)", def = "cp_wizardcloak.png"},
		{name = "FINISHカバー(Hub)", def = "cp_wizardcloak.png"},
		{name = "スロット1(Hub)", def = "メトロノーム"},
		{name = "スロット2(Hub)", def = "打鍵音"},
		{name = "スロット3(Hub)", def = "off"},
		{name = "スロット4(Hub)", def = "off"},
		{name = "スロット5(Hub)", def = "off"},
		{name = "スロット6(Hub)", def = "off"},
		{name = "スロット7(Hub)", def = "off"},
		{name = "スロット8(Hub)", def = "off"},
		{name = "スロット9(Hub)", def = "off"},
		{name = "スロット10(Hub)", def = "off"},
		{name = "ModernChic判定文字(Hub)", def = "#default.png"},
		{name = "ModernChicノーツ(Hub)", def = "#default.png"},
		{name = "ModernChicマイン(Hub)", def = "#default.png"},
		{name = "ModernChicボム(Hub)", def = "clear ring_blue SCUROed..png"},
		{name = "ModernChicフルコンボエフェクト(Hub)", def = "#default.png"},
		{name = "GenericTheme判定文字(Hub)", def = "gridgazer.png"},
		{name = "GenericThemeノーツ(Hub)", def = "default.png"},
		{name = "GenericThemeマイン(Hub)", def = "red.png"},
		{name = "GenericThemeボム(Hub)", def = "explosion.png"},
		{name = "TYPE-M判定文字(Hub)", def = "default.png"},
		{name = "TYPE-Mノーツ(Hub)", def = "default.png"},
		{name = "TYPE-Mボム(Hub)", def = "Type_M.png"},
		{name = "TYPE-Mフルコンボエフェクト(Hub)", def = "#Default.png"},
		{name = "Rogan判定文字(Hub)", def = "default.png"},
		{name = "Roganノーツ(Hub)", def = "simple.png"},
		{name = "Roganボム(Hub)", def = "default.png"},
		{name = "SocialSkin判定文字(Hub)", def = "default.png"},
		{name = "SocialSkinノーツ normal(Hub)", def = "default.png"},
		{name = "SocialSkinボム animation1(Hub)", def = "default.png"},
		{name = "SocialSkinボム wave1(Hub)", def = "default.png"},
		{name = "SocialSkinボム particle1(Hub)", def = "default.png"},
		{name = "SocialSkinボム animation2(Hub)", def = "blank.png"},
		{name = "SocialSkinボム wave2(Hub)", def = "blank.png"},
		{name = "SocialSkinボム particle2(Hub)", def = "default.png"},
		{name = "hij_simple判定文字(Hub)", def = "original.png"},
		{name = "OADX+判定文字(Hub)", def = "off.png"},
		{name = "OADX+ノーツ(Hub)", def = "off.png"},
		{name = "OADX+ヘルチャージノーツ(Hub)", def = "off.png"},
		{name = "OADX+ボム(Hub)", def = "off.png"},
		{name = "OADX+フルコンボエフェクト(Hub)", def = "off.png"},
		{name = "W-mix判定文字 Wide(Hub)", def = "off.png"},
		{name = "W-mix判定文字 AC(Hub)", def = "off.png"},
		{name = "W-mixノーツ Wide(Hub)", def = "off.png"},
		{name = "W-mixヘルチャージノーツ Wide(Hub)", def = "off.png"},
		{name = "W-mixノーツ AC(Hub)", def = "off.png"},
		{name = "W-mixヘルチャージノーツ AC(Hub)", def = "off.png"},
		{name = "W-mixフルコンボエフェクト(Hub)", def = "off.png"},
	},
	offset = {
		{name = "-- 拡張機能 --"},
		{name = "-- Hub設定 --"},
		{name = "-- ModernChic設定 --"},
		{name = "ModernChicボム表示倍率(Hub)(%)", x = 0},
		{name = "ModernChic判定文字表示倍率(Hub)(%)", x = 0},
		{name = "-- GenericTheme設定 --"},
		{name = "GenericThemeボム表示倍率(Hub)(%)", x = 0},
		{name = "GenericTheme判定文字表示倍率(Hub)(%)", x = 0},
		{name = "-- TYPE-M設定 --"},
		{name = "TYPE-Mボム表示倍率(Hub)(%)", x = 0},
		{name = "TYPE-M判定文字表示倍率(Hub)(%)", x = 0},
		{name = "-- Rogan設定 --"},
		{name = "Roganボム表示倍率(Hub)(%)", x = 0},
		{name = "Rogan判定文字表示倍率(Hub)(%)", x = 0},
		{name = "-- SocialSkin設定 --"},
		{name = "SocialSkinボム表示倍率(Hub)(%)", x = 10},
		{name = "SocialSkin判定文字表示倍率(Hub)(%)", x = 0},
		{name = "-- hij_simple設定 --"},
		{name = "hij_simple判定文字表示倍率(Hub)(%)", x = 0},
		{name = "-- OADX+設定 --"},
		{name = "OADX+ボム表示倍率(Hub)(%)", x = 0},
		{name = "OADX+判定文字表示倍率(Hub)(%)", x = 0},
		{name = "-- W-mix設定 --"},
		{name = "W-mix判定文字表示倍率(Hub)(%)", x = 0},
	}
}